### ISSUE TITLE
Utiliser node portable pour lancer l'appli

### ISSUE THREAD

**Issue by ebriand** [frinyvonnick/electron-workshop#25]

**Comment by k33g** [comment]
> WIP
> 👋  @frinyvonnick @ebriand 

# Portable Node-npm-electron

## Linux
- Download node: http://nodejs.org/dist/latest/
- Create a script shell `setup_node.sh`:
  
  ```
  export NODE_HOME=~/where-is-your-node-directory
  export PATH=$NODE_HOME/bin:$PATH
  ```
- `chmod +x setup_node.sh`
- Run it: `. setup_node.sh` _:warning: note the `dot` `space` notation ("when you set an environment variable inside a script, that change is effective only within the script", so this is a workaround)_
- Create a directory, eg: `electron-workshop` an then:

```
cd electron-workshop
npm install electron --save-dev
```
- then create a new script shell (or update `setup_node.sh`)

```
export NODE_HOME=~/where-is-your-node-directory
export PATH=$NODE_HOME/bin:$PATH
export ELECTRON_HOME=~/electron-workshop/node_modules/electron
export PATH=$ELECTRON_HOME/dist:$PATH
```
- Before working with electron, run it: `. setup_node.sh` _:warning: note the `dot` `space` notation_

> Remark: in fact you can create since the first step a file with this content:

```
export NODE_HOME=~/where-is-your-node-directory
export PATH=$NODE_HOME/bin:$PATH
export ELECTRON_HOME=~/electron-workshop/node_modules/electron
export PATH=$ELECTRON_HOME/dist:$PATH
```

> TODO: get all versions of node

### Remark
- :warning: I use the same install of electron for all application, bad idea, we can'e do that with OSX
- first try on **PepperMint** linux distribution :+1: (launch a `hello-world` electron app with `npm start`)
- process reproduced on Ubuntu :+1:
- copy all files on other Ubuntu VM instance, run it :+1:

## OSX
- Download node: http://nodejs.org/dist/latest/
- Create a script shell `setup_node.sh`:
  
  ```
  export NODE_HOME=~/where-is-your-node-directory
  export PATH=$NODE_HOME/bin:$PATH
  ```
- `chmod +x setup_node.sh`
- Run it: `. setup_node.sh` _:warning: note the `dot` `space` notation ("when you set an environment variable inside a script, that change is effective only within the script", so this is a workaround)_
- Create a directory, eg: `electron-app-01` an then:

```
cd electron-app-01
npm install electron --save-dev
```
- create an electron app, run it: `npm start`
- :warning:, we have to install electron in each application directory (I have not managed to do otherwise)

## Windows

> WIP

**Comment by k33g** [comment]
@frinyvonnick @ebriand je ne sais même pas pourquoi j'ai écrit ça en 🇬🇧  (je fais plusieurs choses en même temps ...)

pour le moment ma conclusion serait qu'il va falloir autant d'install Electron que de répertoires étapes. Sous OSX je n'arrive pas à utiliser une seule install d'Electron contrairement à Linux 

reste Windows, je regarderais plus tard

et après je teste avec le starterkit de @frinyvonnick

**Comment by ebriand** [comment]
@k33g avec un lien symbolique ça peut pas le faire pour avoir un seul electron ?

**Comment by k33g** [comment]
@ebriand je teste ça après l'apéro ... le repas pardon

**Comment by k33g** [comment]
@ebriand en fait je ne comprend pas où il va chercher `electron`
- sous Linux c'est dans `node_modules/electron/dist`
- sous OSX dans `dist` il n'y a pas `electron` mais `Electron.app`

🤔  ou alors il faut que je fasse un lien vers le contenu de `Electron.app` .... je reviens

**Comment by frinyvonnick** [comment]
Electron.app c'est un asar non ?

**Comment by k33g** [comment]
@ebriand bingo, alors avec le lien symbolique je n'y arrive pas mais avec ça, ça fonctionne:

```
export NODE_HOME=~/Desktop/_ELECTRON_/osx/node-v6.7.0-darwin-x64
export PATH=$NODE_HOME/bin:$PATH
export ELECTRON_HOME=~/Desktop/_ELECTRON_/osx/electron-workshop/node_modules/electron/dist/Electron.app/Contents/MacOS/
export PATH=$ELECTRON_HOME:$PATH
```

oui je sais, c'est laid de faire ça sur mon desktop

**Comment by k33g** [comment]
@frinyvonnick c'est le format de packaging des apps Apple (je ne connaissais pas **asar** jusqu'à aujourd'hui)

**Comment by k33g** [comment]
## Windows
- download http://nodejs.org/dist/latest-v6.x/node-v6.7.0-win-x64.zip
- unzip it
- set nodejs path:

![image](https://cloud.githubusercontent.com/assets/491848/18994922/418398fe-872a-11e6-923a-4c9061d5d7ac.png)
- add it to the path

![image](https://cloud.githubusercontent.com/assets/491848/18994990/8bf762c6-872a-11e6-8c6f-4f670c19a1cf.png)
- open a console window (installation of electron)

```
md electron-workshop
cd electron-workshop
npm install electron --save-dev
```
- set electron path:

![image](https://cloud.githubusercontent.com/assets/491848/18995282/de4618be-872b-11e6-96a1-d4b451669658.png)
- add it to the path

![image](https://cloud.githubusercontent.com/assets/491848/18995321/fdb18742-872b-11e6-8c28-03be1045c6a4.png)
- then open a console, go to the sample directory, type `npm start`, that's all

![image](https://cloud.githubusercontent.com/assets/491848/18995461/8efd3480-872c-11e6-9d97-5f992d26413f.png)

### Same thing with cmd
- create a file named `setup-node-electron.cmd` or what ever:

```
set NODE_HOME=C:\node-v6.7.0-win-x64
set ELECTRON_HOME=C:\Users\k33g\electron-workshop\node_modules\electron\dist
set PATH=%PATH%;%NODE_HOME%;%ELECTRON_HOME%;
```
- you have to dezip `node-v6.7.0-win-x64.zip`
- you have to install electron: `npm install electron --save-dev`

**Comment by k33g** [comment]
@frinyvonnick @ebriand, ça semble fonctionner sur les 3 plateformes
du coup je packagerais qq chose plus tard avec les assets de @frinyvonnick pour tester plus loin

**Comment by frinyvonnick** [comment]
T'es un champion !

**Comment by k33g** [comment]
attendons de voir si ça fonctionne dans tous les cas ;)

**Comment by k33g** [comment]
nouvelle issue sur le sujet #27 du coup @frinyvonnick à mon avis tu peux clore celle-ci
